### ISSUE TITLE
Publish new PyPi Release

### ISSUE THREAD

**Issue by jasminhacker** [AsbjornOlling/mopidyapi#11]
First of all, thank you a lot for creating this module. It makes interfacing with mopidy from python code so much easier.

Since the release of version 1.0.1 in April, this project improved quite a bit. The thing I'm most interested in is the automatic reconnect on network loss. I restart mopidy quite often, and mopidyapi does not always keep the connection.
Would it be possible to publish a new PyPi package containing these changes?

**Comment by jasminhacker** [comment]
There is now [a fork](https://github.com/raveberry/mopidyapi) and a [pypi package](pypi.org/project/raveberry-mopidyapi/) from the current git. I'd be happy to delete them and move back to the original package when it gets updated.

**Comment by AsbjornOlling** [comment]
Sorry, I didn't act on this until now.
I moved most of my work to gitlab these days, so I quite easily miss things on github sometimes...

Either way, I published a new version to pypi now!
