### ISSUE TITLE
flask_object not created if = None in MopidyWSClient 

### ISSUE THREAD

**Issue by lucblender** [AsbjornOlling/mopidyapi#2]
If not using flask, the self.flask_object of MopidyWSClient is never initialized and make the library crash at line 86 of  MopidyWSClient.
Quick fix is to initilize it in the constructor with 

> self.flask_object = flask_object

 before

>  if flask_object is not None:

**Comment by AsbjornOlling** [comment]
Sorry it took me so long to get to this. I hadn't realized that anyone was actually using this, so didn't think to check.. heh

Should be fixed with commit e6f26a5 :)
Thanks so much for contributing the issue.

Intend to look into ensuring that it still works with Mopidy3 soon.
